# Generated by Django 3.0.8 on 2020-08-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('preference', models.CharField(blank=True, max_length=50, unique=True)),
                ('preference_id', models.AutoField(primary_key=True, serialize=False)),
                ('tags', models.ManyToManyField(blank=True, related_name='preferences', to='tag.Tag')),
            ],
            options={
                'ordering': ['preference'],
            },
        ),
    ]
