# Generated by Django 3.0.8 on 2020-08-18 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preferences',
            options={'ordering': ['preference_id']},
        ),
    ]
