# Generated by Django 3.0.8 on 2020-08-17 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_id',
            new_name='articleid',
        ),
    ]
