# Generated by Django 3.0.8 on 2020-08-17 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200817_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='articleid',
            new_name='article_id',
        ),
    ]
