# Generated by Django 3.0.8 on 2020-08-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag', models.CharField(blank=True, max_length=50)),
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('articles', models.ManyToManyField(blank=True, related_name='tags', to='article.Article')),
            ],
            options={
                'ordering': ['tag_id'],
            },
        ),
    ]
